/*
 * demo
 *
 * simple demo for testing android
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	pk "./app"
)

func main() {
	log.Printf("Server V1.3 started")
	log.Println("working at IP", pk.ListWlan())
	router := pk.NewRouter()
	log.Fatal(http.ListenAndServe(":8080", router))
}
