/*
 * demo
 *
 * simple demo for testing android
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package app

import (
	"fmt"
	"os/exec"
	"strings"

	"net/http"

	fc "./apk"
	dv "./device"
)

//ListWlan method output the wlan info of the host android devices
func ListWlan() string {
	cmd := exec.Command("ifconfig", "wlan0")
	out, err := cmd.CombinedOutput()
	if err != nil {
		fmt.Println("get wlan info failed:", err)
	}
	return getWlan(string(out))
}

func getWlan(info string) string {
	wlanHead := "inet addr"
	wlanEnd := "Bcast"
	start := strings.Index(info, wlanHead)
	end := strings.Index(info, wlanEnd)
	return info[start+len(wlanHead)+1 : end]
}

//InstallPackage for method to install apk file
func InstallPackage(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	switch r.Method {
	case "GET":
		// fmt.Println("Parse html file...")
		fmt.Fprintf(w, "Please post the path of the apk to install")
	case "POST":
		fc.InstallApk(w, r)
	}
}

//OpenPackage  Method to open specific file
func OpenPackage(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	switch r.Method {
	case "GET":
		// fmt.Println("Parse html file...")
		fmt.Fprintf(w, "Please post the package to open")
	case "POST":
		fc.OpenApk(w, r)
	}
}

//ShowPackage method show all package avaliable
func ShowPackage(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	fc.ShowApk(w, r)
}

//Battery method shows info of Battery
func Battery(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	dv.ShowBattery(w, r)
}

//Screen method shows info of Screen
func Screen(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	dv.ShowScreen(w, r)
}

//System method shows info of system
func System(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	dv.ShowSystem(w, r)
}
